import { Injectable } from '@angular/core'
import { FaqQuestion } from 'app/shared/shared.module';


@Injectable()
export class QuestionsService {
    questions: Array<FaqQuestion> = [
        //Fiscal
        new FaqQuestion('¿Cada cuánto tiempo se presentan las declaraciones fiscales?', 'En general tratándose de empresas no consideradas como "gran empresa" las declaraciones de IRPF e IVA se presentan trimestralmente. Además con carácter anual se presentan los resúmenes de IRPF, IVA y el Impuesto sobre Sociedades. Nosotros nos ocupamos de preparar las liquidaciones, anticiparle el resultado de las mismas y en su caso presentarlas en Hacienda'),
        new FaqQuestion('¿Qué impuestos tiene que pagar una Sociedad?', 'Con carácter general debe ingresar las cantidades retenidas ya sea a sus trabajadores, o a los profesionales con los que colabore. También debe ingresar las retenciones por alquiler o rendimientos del capital mobiliario que haya pagado, en su caso. Igualmente debe pagar el importe que resulte de restar el IVA soportado, al IVA que haya repercutido. En función de la marcha del negocio y si ha obtenido beneficios deberá pagar en concepto de Impuesto sobre Sociedades, cantidades que oscilan entre el 20% y el 30%, dependiendo de diferentes factores.. '),
        new FaqQuestion('¿Qué requisitos se deben cumplir para que sea aplicable el supuesto de inversión del sujeto pasivo en las ejecuciones de obra a efectos de IVA?', 'Para que sea aplicable la inversión del sujeto pasivo se deben cumplir los siguientes requisitos: \n a) El destinatario de las operaciones sujetas al Impuesto debe actuar con la condición de empresario o profesional. \n b) Las operaciones realizadas deben tener por objeto la urbanización de terrenos o la construcción o la rehabilitación de edificaciones.\n c) Las operaciones realizadas deben tener la naturaleza jurídica de ejecuciones de obra, con o sin aportación de materiales, incluida la cesión de personal necesario para su realización.\n\ d) Tales operaciones deben ser consecuencia de contratos directamente formalizados entre el promotor y él o los contratistas principales, si bien, la inversión del sujeto pasivo también se producirá, en los casos de ejecuciones de obra y cesiones de personal efectuadas por el contratista principal o otros subcontratistas, cuando las mismas sean consecuencia o lleven causa en un contrato principal, que tenga por objeto la urbanización de terrenos o la construcción o la rehabilitación de edificaciones.'),
        new FaqQuestion('¿En qué casos hay obligación de expedir factura?', 'Los empresarios o profesionales están obligados a expedir factura y copia de esta por las entregas de bienes y prestaciones de servicios que realicen en el desarrollo de su actividad, incluidas las no sujetas y las exentas. También deben expedir factura en los supuestos de pagos anticipadas, excepto en las entregas intracomunitarias de bienes exentos. Deberá expedirse factura en todo caso en las siguientes operaciones:\n a) Si el destinatario es empresario o profesional o cuando así lo exija para el ejercicio de cualquier derecho de naturaleza tributaria.\n b) En las entregas intracomunitarias.\n c) En ventas a distancia localizadas en España.\n d) En las exportaciones, excepto tiendas libres de impuestos.\n e) En las entregas de bienes localizados en España para ser objeto de instalación previa en este territorio.\n f) Si el destinatario es una persona jurídica no empresario o una administración pública.'),
        new FaqQuestion('¿En qué supuesto es posible expedir facturas simplificadas?', 'Podrá expedir factura simplificada en los siguientes supuestos: \nFacturas cuyo importe no supere los 400€ (IVA incluido) \n Facturas rectificativas\n Operaciones en las que el reglamento de de Facturación aprobado por el RD 1496/2003, permitiría la expedición de tikets. En concreto, cuando su importe no exceda de 3.000€ IVA incluido: \na) Ventas al detalle. \n b) Ventas o servicios en ambulancia.\n c) Ventas o servicios a domicilio del consumidor.\n d) Transporte de personas y sus equipajes.\n e) Servicios de hostelería y restauración y suministros de bebidas o comidas para consumir en el acto.\n f) Servicios prestados por salas de baile y discotecas.\n g) Servicios telefónicos prestados mediante la utilización de cabinas telefónicas de uso público, así como mediante tarjetas que no permitan la identificación del portador.\n h) Servicios de peluquería y los prestados por institutos de belleza.\n i) Utilización de instalaciones deportivas.\n j) Revelado de fotografías y servicios prestados por estudios fotográficos.\n k) Aparcamiento y estacionamiento de vehículos.\n l) Alquiler de películas.\n m) Servicios de tintorería y lavandería.\n n) Utilización de autopistas de peaje. \n -los autorizados por el Departamento de Gestión Tributaria' ),
        new FaqQuestion('¿Cuál es el contenido obligatorio de una factura completa?', 'Las facturas completas tendrán los siguientes requisitos:\n a) Numero, y si procede, serie\n b) Fecha de expedición y fecha de la operación, cuando estas no coincidan\n c) Nombre y apellidos, o denominación social completa del expendedor y del destinatario.\n d) NIF del expedidor, también el NIF del destinatario en los casos de:\n -entregas intracomunitarias exentas\n -Inversión del sujeto pasivo\n -Operaciones realizadas al territorio de aplicación del Impuesto por un expedidor establecido en este territorio.\n e) Domicilio del expedidor y destinatario\n f) Descripción de las operaciones\n g) Tipos de los impositivos aplicados\n h) Cuota repercutida  Existen otras obligaciones que deben aparecer en la factura cuando:\n - La operación esté exenta.\n - Se trate de entregas intracomunitarias exentas de medios de transporte nuevos.\n - El adquiriente o destinatario sea quien expide la factura en lugar del proveedor o prestador.\n - El Sujeto pasivo del Impuesto sea el adquiriente o el destinatario de la operación (se hará constar el nombramiento del Sujeto pasivo).\n - Se apliquen los regímenes especiales de las agencias de viajes o de los bienes usados, objetos de arte, antigüedades y objetos de colección o el régimen especial del criterio de caja.'),
        new FaqQuestion('¿Qué es el Sistema de Suministro Inmediato de información (SII)?', 'El Suministro Inmediato de Información (SII) es un nuevo sistema de gestión del IVA que obligará a presentar online a la Agencia Tributaria (AEAT) los detalles de las facturas emitidas y recibidas en un plazo máximo de 4 días hábiles. \n \nEl Sistema SII, cuya entrada en vigor será el 1 de julio de 2017, modifica el sistema actual de llevanza de los libros de registro del IVA y obligará a enviar telemáticamente a la Sede Electrónica de la AEAT los datos de las facturas emitidas y recibidas - incluidas las facturas simplificadas o tiques - en los 4 días siguientes a su emisión o registro contable.'),
        new FaqQuestion('¿Estoy obligado a declarar si he trabajado solo en una empresa?','No deben declarar los contribuyentes que obtengan exclusivamente rendimientos del trabajo que no superen los 22.000 euros anuales de una sola empresa, o bien de más de un pagador si la suma de lo percibido del segundo y siguientes no superan los 1.500 euros anuales.'),
        new FaqQuestion('¿Estoy obligado a declarar si he trabajado en más de una empresa?', 'No hay obligación de declarar si solo se obtienen rendimientos del trabajo de dos o más empresas con el límite conjunto de 11.200 euros anuales. Para el 2015 el limite se elevó a 12.000€.'),
        new FaqQuestion('Soy profesional autónomo, ¿Que retención me tienen que aplicar?', 'Siempre que no hayas realizado la actividad con anterioridad, el año de inicio y los 2 siguientes el 7%, después el 15%.'),
        new FaqQuestion('¿Qué capital mínimo necesito para constituir una sociedad?', '- Para las sociedades anónimas, 60.000€, desembolsando como mínimo el 25%.\n- Para las sociedades limitadas, 3.000€ totalmente desembolsados.'),
        new FaqQuestion('¿Durante cuánto tiempo debo conservar la documentación de mi negocio?', 'Los empresarios conservaran los libros, correspondencia, documentación y justificantes relativos  a su negocio, debidamente ordenados, durante 6 años, a partir del último apunte realizado en los libros, excepto lo que establezca por disposiciones generales o especiales.'),

        //Laboral
        new FaqQuestion('¿Qué es necesario para poder dar de alta a un trabajador?','DNI / NIE\nNº Seguridad Social\nCondiciones laborales (jornada, puesto de trabajo, tipo de contrato, horario, salario, etc)\n¿y si el trabajador es Extranjero? \nAdemás, se deberá aportar NIE con permiso de trabajo en vigor.'),
        new FaqQuestion('¿Qué días son festivos y no trabajamos este año 2017?', '— 6 de enero (viernes), Epifanía del Señor.\n— 13 de abril, Jueves Santo.\n— 14 de abril, Viernes Santo.\n— 1 de mayo (lunes), Fiesta del Trabajo.\n— 15 de agosto (martes), Asunción de la Virgen.\n— 12 de octubre (jueves), Fiesta Nacional de España.\n— 1 de noviembre (miércoles), Todos los Santos.\n— 6 de diciembre (miércoles), Día de la Constitución Española.\n— 8 de diciembre (viernes), Día de la Inmaculada Concepción.\n25 de diciembre (lunes), Natividad del Señor.\n\n\nA estos días hay que sumar 4 días más de las cuales, 2 las establece la Comunidad Autónoma y las otras 2, la localidad en la que se ubique el centro de trabajo.'),
        new FaqQuestion('¿Puedo dar formación a mis trabajadores de forma gratuita?', 'Sí, dispones de un crédito anual gestionado por la Fundación Tripartita.'),
        new FaqQuestion('¿Qué modalidad de despidos puedo realizar?', 'Despido Objetivo: cuando concurran causas económicas, técnicas, organizativas o de producción que lo justifiquen. En este caso el trabajador recibirá una indemnización de 20 días por año trabajado con un límite de 24 mensualidades.\nDespido Disciplinario: cuando el trabajador incurra en una falta muy grave tipificada en el Convenio Colectivo. El trabajador no recibirá indemnización alguna.\n\nDespido Improcedente: Ambos despidos pueden convertirse en un despido improcedente siempre y cuando el trabajador demande y así lo reconozca la empresa en el SMAC o bien, si así lo declara un juez. En el primer caso, el trabajador recibirá una indemnización de 33 días de salario por año trabajado con un límite de 24 mensualidades, en el segundo caso, la empresa podrá optar entre readmitir al trabajador  y pagarle salarios de tramitación o bien, pagarle la indemnización indicada.\n\nFinalización de contrato temporal: Además, cuando un contrato de trabajo temporal finaliza, el trabajador tiene derecho a recibir una indemnización de 12 días de salario por año trabajado.'),
        new FaqQuestion('Si un trabajador está de baja, ¿me sigue costando dinero? ', 'Sí. \nSi el trabajador se encuentra de baja por Enfermedad común, la  cotización se sigue pagando durante todo el proceso de IT y la prestación será abonada por la empresa hasta el 20º día de la baja. Si está de baja por Accidente de trabajo, la  cotización se sigue pagando.')
    ]

    constructor() { }

    getQuestions() {
        return this.questions;
    }

}
